apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: cert-manager-issuer-sample
spec:
  targetResource:
    apiVersion: cert-manager.io/v1
    kind: Issuer
  title: Example Self-Signed Issuer
  description: A simple self-signed Issuer for development and testing
  yaml: |-
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: selfsigned-issuer
      namespace: default
    spec:
      selfSigned: {}

