apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-istio-csr
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager-istio-csr
    app.kubernetes.io/instance: cert-manager-istio-csr
    app.kubernetes.io/version: v0.15.0
    app.kubernetes.io/managed-by: cert-manager-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-istio-csr
  template:
    metadata:
      labels:
        app: cert-manager-istio-csr
        app.kubernetes.io/name: cert-manager-istio-csr
        app.kubernetes.io/instance: cert-manager-istio-csr
        app.kubernetes.io/version: v0.15.0
    spec:
      serviceAccountName: cert-manager-istio-csr
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: cert-manager-istio-csr
          image: quay.io/jetstack/cert-manager-istio-csr:v0.15.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6443
            - containerPort: 9402
          readinessProbe:
            httpGet:
              port: 6060
              path: /readyz
            initialDelaySeconds: 3
            periodSeconds: 7
          args:
            - --log-level=1
            - --log-format=text
            - --metrics-port=9402
            - --readiness-probe-port=6060
            - --readiness-probe-path=/readyz
            - --certificate-namespace=istio-system
            - --issuer-enabled=true
            - --issuer-name=istio-ca
            - --issuer-kind=Issuer
            - --issuer-group=cert-manager.io
            - --preserve-certificate-requests=false
            - --root-ca-file=
            - --serving-certificate-dns-names=cert-manager-istio-csr.cert-manager.svc
            - --serving-certificate-duration=1h
            - --trust-domain=cluster.local
            - --cluster-id=Kubernetes
            - --max-client-certificate-duration=1h
            - --serving-address=0.0.0.0:6443
            - --serving-certificate-key-size=2048
            - --serving-signature-algorithm=RSA
            - --enable-client-cert-authenticator=false
            - --leader-election-namespace=istio-system
            - --disable-kubernetes-client-rate-limiter=false
            - --runtime-issuance-config-map-name=
            - --runtime-issuance-config-map-namespace=cert-manager
            - --istiod-cert-enabled=false
            - --istiod-cert-name=istiod-dynamic
            - --istiod-cert-namespace=istio-system
            - --istiod-cert-duration=1h
            - --istiod-cert-renew-before=30m
            - --istiod-cert-key-algorithm=RSA
            - --istiod-cert-key-size=2048
            - --istiod-cert-additional-dns-names=
            - --istiod-cert-istio-revisions=default
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
