---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-istio-csr
  namespace: cert-manager
  labels:
    app: cert-manager-istio-csr
    app.kubernetes.io/name: cert-manager-istio-csr
    app.kubernetes.io/instance: cert-manager-istio-csr
    app.kubernetes.io/version: "v0.12.0"
    app.kubernetes.io/managed-by: cert-manager-operator
    app.kubernetes.io/part-of: cert-manager-operator
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 6443
      protocol: TCP
      name: web
  selector:
    app: cert-manager-istio-csr
